development:
  adapter: redis
  url: redis://localhost:6379/

test:
  adapter: async

staging:
  adapter: redis
  url: redis://localhost:6379/rpl_stg

production:
  adapter: redis
  url: redis://localhost:6379/1
