defautl: &default
  point_settings:
    goal: 6.0
    assist: 3.0
    chance_created: 0.0
    pass_completed: 0.0
    played_30_min: 1.0
    played_50_min: 2.0
    played_90_min: 3.0
    yellow_cards: -2.0
    red_cards: -5.0
    goal_conceded: -1.0
    clean_sheet: 5.0
    save: 0.0
    defensive_error: -1.0
    own_goal: -2.0
    cross: 0.0
    tackle_won: 0.5
    interception: 0.0
    penalty_saved: 0.0
    big_chance_missed: 0.0
    turn_over: 0.0
    manager_win: 0.0
    corner_kick_won: 0.0
    penalty_won: 1.0
    penalty_conceded: -1.0
    key_pass: 1.0
    shot_on_target: 0
    penalty_missed: -1
    passes_40: 1
    passes_50: 2
    passes_60: 3
    take_ons: 0
    
  point_mapper:
    goal: "c_goal"
    assist: "c_assist"
    chance_created: "c_chance_created"
    pass_completed: "c_pass_completed"
    played_30_min: "c_g_30_min"
    played_50_min: "c_g_50_min"
    played_90_min: "c_g_90_min"
    yellow_cards: "c_yellow_cards"
    red_cards: "c_red_cards"
    goal_conceded: "c_goal_conceled"
    clean_sheet: "c_clean_sheet"
    save: "c_save"
    defensive_error: "c_defensive_error"
    own_goal: "c_own_goal"
    cross: "c_cross"
    tackle_won: "c_tackle_won"
    interception: "c_interception"
    penalty_missed: "c_penalty_missed"
    penalty_saved: "c_penalty_saved"
    big_chance_missed: "c_big_chance_missed"
    turn_over: "c_turn_over"
    manager_win: "c_manager_win"
    corner_kick_won: "c_corner_kick_won"
    penalty_won: "c_penalty_won"
    penalty_conceded: "c_penalty_conceded"
    key_pass: "c_key_pass"
    net_pass: "c_net_pass"
    shot_on_target: "c_shot_on_target"
    passes_40: "c_passes_40"
    passes_50: "c_passes_50"
    passes_60: "c_passes_60"
    take_ons: "c_take_ons"  

  category_settings:
    goal: 2
    goal_enabled: true

    assists: 1
    assists_enabled: false

    pass_completed: 0
    pass_completed_enabled: true

    pass_percent: 1
    pass_percent_enabled: false

    discipline: 1
    discipline_enabled: true

    goals_conceded: 1
    goals_conceded_enabled: true

    goals_conceded_points: 1
    goals_conceded_points_enabled: false

    clean_sheets: 1
    clean_sheets_enabled: true

    minutes_played: 1
    minutes_played_enabled: false

    minutes_played_points: 1
    minutes_played_points_enabled: true

    key_passes: 1
    key_passes_enabled: true

    tackles_won: 1
    tackles_won_enabled: true

    turnovers: 1
    turnovers_enabled: false

    saves: 1
    saves_enabled: false

    saves_percent: 1
    saves_percent_enabled: true

    net_passes: 1
    net_passes_enabled: true

    interceptions: 1
    interceptions_enabled: false

    shots_on_target: 1
    shots_on_target_enabled: false

    take_ons: 1
    take_ons_enabled: false

    tackle_interception: 1
    tackle_interception_enabled: false

    possession: 1
    possession_enabled: false
  
  category_mapper:
    goal: "c_goal"
    goal_enabled: "is_c_goal"
    assists: "c_assist"
    assists_enabled: "is_c_assist"
    pass_completed: "c_pass_completed"
    pass_completed_enabled: "is_c_pass_completed"
    pass_percent: "c_pass_percent"
    pass_percent_enabled: "is_c_pass_percent"
    discipline: "c_discipline"
    discipline_enabled: "is_c_discipline"
    goals_conceded: "c_goal_conceled"
    goals_conceded_enabled: "is_c_goal_conceled"
    clean_sheets: "c_clean_sheet"
    clean_sheets_enabled: "is_c_clean_sheet"
    minutes_played: "c_minutes"
    minutes_played_enabled: "is_c_minutes"
    key_passes: "c_k_pass"
    key_passes_enabled: "is_c_k_pass"
    tackles_won: "c_tackles"
    tackles_won_enabled: "is_c_tackles"
    turnovers: "c_turn_over"
    turnovers_enabled: "is_c_turn_over"
    saves: "c_save"
    saves_enabled: "is_c_save"
    saves_percent: "c_save_percent"
    saves_percent_enabled: "is_c_save_percent"
    net_passes: "c_net_pass"
    net_passes_enabled: "is_c_net_pass"
    interceptions: "c_interceptions"
    interceptions_enabled: "is_c_interceptions"
    shots_on_target: "c_shots_on_target"
    shots_on_target_enabled: "is_c_shots_on_target"
    take_ons: "c_take_ons"
    take_ons_enabled: "is_c_take_ons"
    tackle_interception: "c_tackle_interception"
    tackle_interception_enabled: "is_c_tackle_interception"
    possession: "c_possession"
    possession_enabled: "is_c_possession"
    minutes_played_points: "c_minutes_played_points"
    minutes_played_points_enabled: "is_c_minutes_played_points"
    goals_conceded_points: "c_goals_conceded_points"
    goals_conceded_points_enabled: "is_c_goals_conceded_points"

test:
  <<: *default

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default

